# Generated by Django 2.0.1 on 2018-01-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20180115_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('canino', 'CANINO'), ('felino', 'FELINO')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('macho', 'MACHO'), ('hembra', 'HEMBRA')], max_length=10, null=True),
        ),
    ]
